%%To Run this file you need to start R
%%Then do:
%>library(tools)
%>Sweave("rcorner.rnw")
%Then you can run latex/pdflatex on the resulting .tex file

%Note: I had to adjust the bounding boxes of the graphics by hand (in
%Adobe Illustrator) since I couldn't figure out how to instruct
%Sweave() to do so (in plain old R, I'd have used the postscript() and
%par() commands).

\documentclass{article}
\setlength{\parindent}{0pt}
\addtolength{\parskip}{.5\baselineskip}
\usepackage{graphicx,multirow,comment,amsmath,natbib,url,here}
\bibliographystyle{apsr}
\usepackage[T1]{fontenc}
\renewcommand\harvardurl[1]{\textsf{\textbf{url:}} \url{#1}}

%Don't automatically number any of the sectioning commands
\setcounter{secnumdepth}{0}
\usepackage[letterpaper,bottom=1in,top=1in,right=1.5in,lmargin=1.5in]{geometry}

\title{Using \R~to Keep it Simple:
  Exploring Structure in Multilevel Datasets}
\author{Jake Bowers \\ Dept of Political Science and Center for
  Political Studies \\ University of Michigan}
\date{Version of \today}

%Create new title appearance
\makeatletter
\def\maketitle{%
  \null
  \thispagestyle{empty}%
  \begin{center}\leavevmode
    \normalfont
    {\large \@title\par}%
    {\large \@author\par}%
    {\large \@date\par}%
  \end{center}%
  \null
  }
\makeatother

%%Make a references to the R statistical language be in san-serif font.
\newcommand{\R}{\textsf{R}}

%%These next lines tell latex that it is ok to have a single graphic
%%taking up most of a page, and they also decrease the space around
%%figures and tables.
\renewcommand\floatpagefraction{.9}
\renewcommand\topfraction{.9}
\renewcommand\bottomfraction{.9}
\renewcommand\textfraction{.1}   
\setcounter{totalnumber}{50}
\setcounter{topnumber}{50}
\setcounter{bottomnumber}{50}
\setlength{\intextsep}{4ex}
\setlength{\floatsep}{2ex}
\setlength{\textfloatsep}{2ex}

\begin{document}
\maketitle
%This next command tells latex to insert figures that take up 95\% of
%the width of the text region.
\setkeys{Gin}{width=0.95\textwidth}

<<datasetup,echo=FALSE>>=

load("WVDATA/fulldat.rda")
##Make id var called id instead of S007
fulldat$id<-fulldat$S007
##Scale educ2 (the version of education with all of secondary education collapsed together) to start at 0
fulldat$educ2<-fulldat$educ2-1

##Data set up
load("WVDATA/pctcollege.rda")
themacrodat<-pctcollege[pctcollege$country %in% levels(fulldat$country),]
rm(pctcollege)

##Education data from:
##Table A2.3. Population that has attained tertiary education (2001)
##Percentage of the population that has attained tertiary-type B education or tertiary-type A and advanced research programmes, by age group.
##www.oecd.org/edu/eag2003

ps.options(width=7,height=7,family="Times",pointsize=10)

options(width=40)                       

library(locfit)
@ 

\emph{Point 1: Before starting \R~have a question you want to answer.}

In the United States, the relationship between education and political
participation in the cross-section is well known: better educated
people tend to be the types that get involved in politics. Extant
theories suggest that this relationship exists because (1) people who
are better educated have more of the skills they need to do the work
of political participation \citep{vsb95} and (2) people who are better
educated are more likely to know other political actors, i.e. they
have higher status in the kinds of social networks that matter for
political involvement \citep{nie96,roha93,huck79}.

If we looked at the relationship between education and participation
in other countries, would these theories travel? Would education as
``civic skills,'' such as knowing how to write letters or chair
meetings, have the same impact on civic activity in a country where
nearly everyone is highly educated as in a country where very few
people are literate?  Probably not. Would education matter as much in
a place where social status is conferred at birth as it does in a
place where social status is tied to a college degree? Probably not.
These suppositions raise the question about what might be determining
who participates across a variety of places, where education plays
different roles in society. Answers to this question might tell us
something new about the societal bases of political activity, as well
as providing new perspectives on 50 years worth of literature based
largely on studies of ordinary citizens in the USA.

The question I posed about whether the theories of political
participation travel is in essence a question about whether a
relationship between variables measured at one level (among ordinary
people) depends in some way on variables measured at another level
(among countries).  This article is written now because we are finally
getting data to address such questions directly on a large scale via
the Comparative Study of Electoral Systems (\citeauthor{cses}), the
World Values Survey (\citeauthor{wvs}), the African/Euro/Latino
Barometers (\citeauthor{afrobarometer,eurobarometer,latinobarometro}),
and others.  Also, within the study of domestic politics, more and
more researchers are gathering data on attributes of both citizens and
the electoral districts or other geographies in which they are
embedded.  In fact, I wager a bottle of Kwak (a Belgian beer) that the
number of articles in political science journals concerned with
quantitative analysis of datasets with more than one type of unit of
analysis has more than doubled in the last 10 years.

A dataset used to answer questions about people nested within
geographies tends to have fewer countries/districts/states (i.e.,
macro-level units) than individuals/towns/firms (i.e., micro-level
units). And analyses based on such datasets tend to focus on how
differences across macro-units somehow condition or influence the
differences within macro-units.\footnote{I am leaving time out of this
  article to keep it simple.} To address the question I posed earlier,
I use the World Values Surveys and European Values Surveys 1999-2001
combined file (ICPSR \# 3975) for the micro-level variables of
educational attainment and political participation. For macro-level
data I use information from the OECD in 2003 on the percent of the
population aged 25 to 64 who have a college degree. Since I am using
these data to illustrate a series of techniques rather than to answer
exhaustively an analytic question, I selected 25 countries, mostly
from Europe, to show high variance in the country-level educational
context. The political participation variable counts the number out of
five possible activities done by individuals in the
surveys.\footnote{The activities are signing a petition, joining in
  boycotts, attending lawful demonstrations, joining unofficial
  strikes, or occupying buildings.} The final dataset contains 36,174
people across 25 countries, and the amount of information available
within countries ranges from 968 people in Iceland to 4607 people in
Turkey (50\% of the countries have between 1015 and 1522 cases). Here
is what the data set looks like for a few survey
respondents:\footnote{The dataset used to produce this article is
  available for download at
  \url{http://www.umich.edu/~jwbowers/papers.html}. The article itself
  was produced using Sweave
  (\url{http://www.ci.tuwien.ac.at/~leisch/Sweave/FAQ.html}). Sweave
  is a system for embedding \R~code and output within a
  \LaTeX~document. That is, this article was produced from one single
  file that contained both text in \LaTeX~format, and chunks of
  \R~code.  Sweave ensures that \R~code is printed out with ``>'' to
  mark the beginning of a command line and a ``+'' to indicate that a
  command line has continued. In the actual \R~code I typed the
  commands without ``>'' or ``+'' characters. See my file for an
  example of how this was done. An excellent introduction to
  \R~syntax can be downloaded from
  \url{http://cran.r-project.org/manuals.html}.}

<<echo=TRUE>>=
##Notice that these comment lines do not appear in the LaTeX document

##Look at the dataset
fulldat[c(1:5,36169:36174),c("country","id","partic","educ2","pctcollege")]
@

This excerpt of the full dataset shows six columns: the row numbers
that are automatically generated by \R; the label of the country in
which the survey took place (\texttt{country}); respondent
identification number (\texttt{id}); number of participatory acts
reported by that person (\texttt{partic}); the educational attainment of
that person (\texttt{educ2}); and the percent of adults aged 25-64 who
have a college degree in that country (\texttt{pctcollege}). Notice that
\texttt{pctcollege} and \texttt{country} are the same for every
respondent within a given country. This is a very common structure for
multilevel datasets.

\emph{Point 2: Plot First, Model Later}

Just to be concrete, say I wonder (1) whether the relationship between
participation and education differs across countries, and (2) if it
does differ, whether the difference could have something to do with
inequality in educational attainment within countries. The motivation
behind the second question is to shed some light on the theory that,
in addition to teaching people civic skills, education matters for
participation because it allocates social status in a society. In a
place where everyone has a college degree, we would not expect
education to distinguish participators from non-participators.

The techniques I propose here are meant as a prelude to any
statistical procedures that might be suggested to estimate
coefficients and related stars (err, standard errors). These
techniques will help you decide which kind of analysis you will
eventually want to conduct and which modeling assumptions are more or
less tenable. The idea is simple: run a regression for each
country and then plot the coefficients.\footnote{This idea is not new
  to me or really that new in general. For great conversations about
  this, though, I should thank Chris Achen, Steve Heeringa, Dave
  Howell, Karen Long Justo, and Phil Shively and the Comparative Study
  of Electoral Systems for hosting us all for a day.  Michael Herron
  and Cara Wong provided important comments and criticisms on this
  article. And \citet{long2004} presents some other ways to plot
  within country coefficients in the context of presenting a
  meta-analysis style approach to estimating the effects of
  country-level characteristics on individual-level outcomes.} The
idea of running 25 different regressions, one per country, and making
at least 25 different plots is enough to make most peoples' eyes glaze
over. This is where \R~\citep{rlang} makes life much easier. The
following 2 lines of \R~code run 25 regressions, collect the 25
regression objects in a list named \texttt{theregs}, and add names
to the list object for the appropriate countries (naming things turns
out to make life a bit easier down the road).\footnote{This is another
  place where I'm playing a bit fast and loose. The educational
  attainment scale is coded 0=incomplete primary education,
  1=completed primary education, 2=incomplete secondary education,
  3=completed secondary, 4=incomplete university level, and
  5=completed university level. This is not an interval level measure,
  but I am treating it as such for the purpose of illustration here.}

<<regressions,echo=TRUE>>=
##Run a regression of participation on education within each country and collect the results in a list.
theregs<-lapply(unique(fulldat$country),function(x){
  lm(partic~educ2,data=fulldat[fulldat$country==x,])})
##Name the elements of the list after their respective countries.
names(theregs)<-unique(fulldat$country)
@ 

To make things easier for plotting, I collect the coefficients from
the regressions into a matrix called \texttt{coefmat} and the standard
errors into a matrix called \texttt{semat.} Then, I combine coefficients,
standard errors, and country-level information into a data frame that
I can use for plotting. I also make a new macro-level variable called
\texttt{educgroupsQ} which breaks the country-level educational context
variable into three groups --- low, middle, and high. Finally, I print
the first three rows of the \texttt{coefmat} matrix.

<<coefmats,echo=TRUE>>=
coefmat<-matrix(unlist(lapply(theregs,coef)),ncol=2,byrow=TRUE,
                dimnames=list(names(theregs),c("Intercept","Educ")))

semat<-matrix(unlist(lapply(theregs,function(x) summary(x)$coef[,"Std. Error"])),ncol=2,byrow=TRUE,
                dimnames=list(names(theregs),c("SEIntercept","SEEduc")))

coefsedf<-data.frame(coefmat,semat)
coefsedf$country<-factor(row.names(coefsedf))
coefdf<-merge(coefsedf,themacrodat,by="country")
row.names(coefdf)<-as.character(coefdf$country)

coefdf$educgroupsQ<-cut(coefdf$pctcollege,quantile(coefdf$pctcollege,p=c(0,.25,.75,1)),include.lowest=TRUE)

print(coefdf[1:3,],4)
@ 

Figure~\ref{fig:within1} shows the scatter plots of participation by
education within nine of the 25 countries, jittered to show the
density of the points at each coordinate. The panels are plotted in
order of the percent of their population aged 25-64 who have a college
degree (with the United States having the highest proportion and
Austria the lowest). The plots for the countries in the lowest
education group are colored black, the middle group is colored dark
gray, and the highest group is colored light gray. Each panel contains
a regression line (the straight one) and a line connecting the mean
participation levels at each level of educational attainment (the not
straight one).  I included the line of means as a check for non-linear
relationships. The percent attending college in the country is also
printed in each panel.

<<setupfig1,echo=TRUE>>=
##The means
themeans<-tapply(fulldat$partic,list(country=fulldat$country,educ2=fulldat$educ2),
                 function(x) mean(x,na.rm=TRUE))
##Select 9 countries out of the 25.
somecountries<-c("Austria","Brazil","Chile","Spain","Sweden","Japan","Denmark","Norway","United States")
smallcoefdf<-coefdf[coefdf$country %in% somecountries,]
##Make sure that they are listed in order of country level pct college educated.
countriesInOrder<-as.character(smallcoefdf$country[order(smallcoefdf$pctcollege)])
thecols<-gray(c(.10,.5,.80)) ##low, medium, high
quartz() ##This is a graphics device on OS X. You may prefer to use x11() or something else depending on your platform.
@ 

\begin{figure}[H]
\begin{center}
<<makefig1,fig=TRUE,width=7,height=7>>=
par(mfrow=c(3,3),pty="s",mar=c(1,1,2,1),mgp=c(1.5,.5,0),oma=c(3,3,0,0));ps.options(pointsize=12)
for(i in countriesInOrder){
  plot(jitter(fulldat[fulldat$country==i,"educ2"]), 
       jitter(fulldat[fulldat$country==i,"partic"]),type="p",
       col=thecols[unclass(coefdf[i,"educgroupsQ"])],xlab="",ylab="",
       xlim=range(fulldat$educ2,na.rm=TRUE),ylim=range(fulldat$partic,na.rm=TRUE),cex=1)
  title(main=i,cex=1)
  text(0,4.5,paste("% College=",coefdf[i,"pctcollege"],sep=""),pos=4,font=2,cex=1)
  abline(coef(theregs[[i]]))
  lines(0:5,themeans[i,])
}
mtext(side=1,"Educational Attainment",outer=TRUE,line=1)
mtext(side=2,"Number of Participatory Acts",outer=TRUE,line=1)
@ 
 
\caption{Within Country Regressions and Means Sorted by Proportion of
  the Population with a College Degree}\label{fig:within1}
\end{center}
\end{figure}

The Lattice graphics \citep{lattice} sub-system within \R~provides a
quicker and more elegant way to produce a similar plot.\footnote{The
  manual for Lattice graphics explains: ``Trellis Graphics is a
  framework for data visualization developed at the Bell Labs by Rick
  Becker, Bill Cleveland et al, extending ideas presented in Bill
  Cleveland's 1993 book \emph{Visualizing Data} \citep{cleveland93}.
  Lattice is best thought of as an implementation of Trellis Graphics
  for R.'' \citep{lattice}} Figure~\ref{fig:within2} shows this plot.
It is my experience that lattice graphics (functions like
\texttt{xyplot()}) are usually less flexible than the lower level
plotting commands (e.g., functions like \texttt{plot()}). However, they can
produce reasonable plots more quickly than the lower level commands
--- for example, in this next example, the regressions are run and
plotted with the \texttt{panel.lmline()} function. This means that if
our plotting were to stop here, we wouldn't have needed to create our
dataset of coefficients and standard errors.

<<setupfig1,echo=TRUE>>=
library(lattice)
fulldat$countryEducOrder<-factor(fulldat$country,levels=levels(fulldat$country)[order(coefdf$pctcollege)],ordered=TRUE)
latticeplot<-xyplot(partic~educ2|countryEducOrder,data=fulldat,cex=.7,
                    subset=fulldat$country %in% somecountries,
                    xlab="Education Level",ylab="Number of Participatory Acts",
                    panel=function(x,y,...){
                      panel.xyplot(jitter(x),jitter(y),col="gray",...)
                      panel.lmline(x,y,..)
                      themeans<-tapply(y,x,function(x) mean(x,na.rm=TRUE))
                      llines(as.numeric(dimnames(themeans)[[1]]),themeans,col="black")})
@ 

\begin{figure}[H]
\begin{center}
<<printfig2,fig=TRUE,width=7,height=7>>=
print(latticeplot)
@ 
\caption{Within Country Regressions and Means Sorted by Proportion of
  the Population with a College Degree: Lattice Graphics}\label{fig:within2}
\end{center}
\end{figure}

If we do not have a continuous macro-level variable, we might want to
plot these regression lines groups together --- with the mean line
overlaid. Figure~\ref{fig:grouped} shows the within country
regression lines (bounded at the limits of the education variable)
plotted together within groups defined by the percent of the
population receiving a college degree.\footnote{The thick mean lines do not take into account the
  amount of information that went into the estimation of the different
  lines. I leave the creation of a weighted average line as an
  exercise.}

<<listfits,echo=TRUE>>=
##Produce fitted values for each of the regressions in a list
thefits<-lapply(theregs,function(x){ 
  thenewdata<-range(x$model$educ2)
  data.frame(cbind(x=thenewdata,y=predict(x,newdata=data.frame(educ2=thenewdata))))
})
@ 

\begin{figure}[H]
\begin{center}
<<groupedfig,fig=TRUE,width=7,height=3>>=
ps.options(width=7,height=3,family="Times",pointsize=10)
par(mfrow=c(1,3),pty="s",mar=c(1,1,2,1),mgp=c(1.5,.5,0),oma=c(2,2,0,0))
for(i in levels(coefdf$educgroupsQ)){
  plot(range(fulldat$educ2,na.rm=TRUE),range(unlist(lapply(thefits,function(x) range(x$y)))),
       type="n",xlab="",ylab="",main=paste("Range % College=",i))
  lapply(thefits[coefdf$educgroupsQ==i],function(x){
    lines(x$x,x$y,col=gray(.5))})
  tempdf<-data.frame(thefits[coefdf$educgroupsQ==i])
  meanpartic<-rowMeans(tempdf[,grep("y$",names(tempdf))])
  lines(c(0,5),meanpartic,lwd=3)
}
mtext(side=1,"Educational Attainment",outer=TRUE)
mtext(side=2,"Number of Acts",outer=TRUE,line=1)

@ 
\caption{The Relationship between Educational Attainment and  Political
  Participation by Educational Context of
  Countries}\label{fig:grouped}
\end{center}
\end{figure}

Now let us look at the change in the individual level effects of
education on participation by the country-level educational attainment
level more systematically. Since we have collected the coefficients
and standard errors in a dataset, we can look at how the
relationship between education and participation varies across
countries based on the educational inequality at the country-level, by
treating these coefficients as data and the standard errors as weights.

Figure~\ref{fig:coefs} shows the coefficients from within country
regressions plotted against the percent of college educated within a
country. The line segments through each point show the $\pm$2 standard
error range around each point --- to alert us to the amount of
information used in the calculation of that estimate. The straight
lines in each panel show the regression of the coefficients on country
level education. The wiggly lines are a non-parametric regression. And,
points that fall far from the regression line are labeled. Both the
linear regression and the non-parametric smoother are weighted by the
standard errors of the within country regressions.



\begin{figure}[H]
\begin{center}
<<coefgraphs,echo=TRUE,fig=TRUE,width=7,height=4>>=
##More direct estimate of the change in slope and/or intercept by mean educ level of the country
EducOnPctCollW<-lm(Educ~pctcollege,data=coefdf,weights=1/SEEduc)
interceptOnPctCollW<-lm(Intercept~pctcollege,data=coefdf,weights=1/SEIntercept)

ps.options(width=7,height=4,family="Times",pointsize=10)
attach(coefdf)
par(mfrow=c(1,2),pty="s",mar=c(2,3,2,1),mgp=c(1.5,.5,.0),oma=c(2,0,0,0))
plot(pctcollege, Educ,type="p",ylim=range(Educ-2*SEEduc,Educ+2*SEEduc),main="Slopes",xlab="",ylab="Effect on Participation")
segments(pctcollege,Educ-2*SEEduc,pctcollege,Educ+2*SEEduc)
abline(EducOnPctCollW)
plot(locfit(Educ~pctcollege,data=coefdf,weights=1/SEEduc,alpha=1/2),add=TRUE)
weirdpoints<-abs(resid(EducOnPctCollW))>quantile(abs(resid(EducOnPctCollW)),p=c(.85))
text(pctcollege[weirdpoints],Educ[weirdpoints],as.character(country)[weirdpoints])

plot(pctcollege, Intercept,type="p",ylim=range(Intercept-2*SEIntercept,Intercept+2*SEIntercept),main="Intercepts",xlab="",ylab="Mean Participation")
segments(pctcollege,Intercept-2*SEIntercept,pctcollege,Intercept+2*SEIntercept)
abline(interceptOnPctCollW)
plot(locfit(Intercept~pctcollege,data=coefdf,weights=1/SEIntercept,alpha=1/2),add=TRUE)
weirdpoints2<-abs(resid(interceptOnPctCollW))>quantile(abs(resid(interceptOnPctCollW)),p=c(.85))
text(pctcollege[weirdpoints2],Intercept[weirdpoints2],as.character(country)[weirdpoints2])

mtext(side=1,"Percent of Population 25-64 years old with a College Degree",outer=TRUE,line=0)
detach(coefdf)
@ 
\caption{The Relationship Between Education and Participation as a
  function of the Educational Inequality Of A Country}\label{fig:coefs}
\end{center}
\end{figure}

In the slopes panel, we see that the relationship between an
individual's education and her participation does not depend in any
simple linear way on the percent of the population who has a college
degree, although there might be some interesting non-linear pattern.
Furthermore, we see that Japan is not well characterized by the
process that captures the other countries. In the intercepts panel, we
see that countries where more people have college degrees tend to have
higher participation rates among people with low educational
attainment than countries where fewer people have college degrees.  In
other words, it appears that there is a participation benefit that
accrues from living in a place where many people have more education
--- even for people who do not have high educational levels. Both
panels also alert us to the fact that certain countries do not fit the
general patterns very well: Japan stands out for having almost no
relationship between education and participation, and Sweden and
Hungary are places where those with low education appear to
participate more and less, respectively, than would be expected given
the educational context in those countries.

So far, it is also clear that people who have more education are more
likely to get involved in petitions, boycotts, demonstrations, illegal
strikes, and sit-ins than people who have less education, \emph{in
  nearly every country in the dataset}. This result is surprising
given my expectations about how political institutions (and social
status) ought to be differently related to education in different
countries.  We have also seen that Japan does not have a pattern like
the others.  In Japan, in 1999-2001, education did not appear related
to participation at all. Notice that if we had skipped this plotting
step, we would have estimated some kind of model that produced a
coefficient for something like the ``average relationship between
education and participation'' across countries. This coefficient might
have had many stars, or not. And, these plots suggest that an average
slope might do a good job summarizing these patterns (i.e., the slopes
do not look that different across countries). However, the lack of
relationship in Japan would have been smoothed over. Since this is an
article about how to use \R, I will not speculate about what this
result means for Japan or for the overall question I posed at the
beginning of the article. However, it is worth noting that the plots
have taught us something about the phenomenon we care to understand, which would have been hard to pick up in a model specified before
looking at the data.

\emph{Point 3: Plot to Check Assumptions for Future Modeling}

Many popular modeling strategies for multilevel data rely on
assumptions about relationships between the slopes and intercepts in
within country regressions. For example, most ``random effects'' or
``random coefficients'' or ``multilevel'' models (whether estimated
using maximum likelihood or Markov-Chain Monte-Carlo simulation)
assume that the slopes and the intercepts can be thought of as drawn
from a multivariate normal distribution.  How plausible is such an
assumption in this case? A priori, it is hard to know. It is plausible
that we could have some countries with very strong relationships and
others with no relationships --- leading to a bimodal distribution of
slopes. If this were the case, then the assumptions about normally
distributed random coefficients would not be tenable.

The top row of figure~\ref{fig:qqplots} shows qqplots where the slopes
and intercepts are plotted against what would be expected, were these
variables drawn from a normal distribution. The bottom row shows the
non-parametric density estimates for the slopes and intercepts.
Overall, the slopes and intercepts do look like they could have been
drawn from a normal distribution, for a few outlying points.

\begin{figure}[H]
\begin{center}
<<margdists,echo=TRUE,fig=TRUE,width=7,height=7>>=

par(mfrow=c(2,2),pty="s",mar=c(3,2,2,1),oma=c(0,0,0,0))
qqnorm(coefdf$Intercept,main="Are Intercepts Like a Normal Distribution?");qqline(coefdf$Intercept)
qqnorm(coefdf$Educ,main="Are Slopes Like a Normal Distribution?");qqline(coefdf$Educ)

plot(density(coefdf$Intercept),main="Density of Intercepts");rug(coefdf$Intercept)
plot(density(coefdf$Educ),main="Density of Slopes");rug(coefdf$Educ)
@ 
\caption{Assessing the Marginal Distributions of the Slopes and Intercepts}\label{fig:qqplots}
\end{center}
\end{figure}

What kind of multivariate normal distribution generated these
marginally (mostly) normal-looking slopes and intercepts? Are the
slopes and intercepts correlated with one another?
Figure~\ref{fig:jointdist} shows the joint distribution of the slopes
and intercepts. The smoothed contour lines representing bivariate
density are overlaid on the scatterplot of the slopes and intercepts.
We do not see an extremely strong relationship here, and the
correlation is -.13. This suggests that countries where people with
lower education participate more (i.e., higher intercepts) tend
(weakly) to be countries where the relationship between education and
participation is weaker than in countries where the least educated
participate less.

\setkeys{Gin}{width=0.5\textwidth}
\begin{figure}[H]
\begin{small}
\begin{center}
<<jointdists,echo=TRUE,fig=TRUE,width=3,height=3>>=
ps.options(width=3,height=3,family="Times",pointsize=10)
par(mfrow=c(1,1),pty="s",oma=c(0,0,0,0),mar=c(3,2,1,1),mgp=c(1.5,.5,0))
plot(coefdf$Intercept,coefdf$Educ,pch=19,col="black",xlab="Intercepts",ylab="Slopes",cex.lab=1)
plot(locfit(~Intercept*Educ,data=coefdf,alpha=3/4,scale=T,kern="rect",deg=2,family="dens"),
     add=TRUE,col=gray(.5),drawlabels=TRUE)
text(coefdf$Intercept[coefdf$country %in% c("Japan","Sweden")],
     coefdf$Educ[coefdf$country %in% c("Japan","Sweden")],
    c("Japan","Sweden"),pos=2)
@ 
\caption{Assessing the Joint Distribution of Slopes and Intercepts}\label{fig:jointdist}
\end{center}
\end{small}
\end{figure}

Pretend that these plots were done on a dataset with all of
the countries in the World Values Survey, and that within country
models included appropriate controls for variables that might be
confounding the relationship between education and participation. And,
pretend that I had multiple measures of the educational inequality
within these countries. If I saw results like those shown here, I
would have a story to tell about the expectations that were generated
from the previous theories: The theories appear to travel well
although educational inequalities in participation appear to be
slightly ameliorated within countries where more of the population is
better educated. I would also have new questions to spur further
research --- what is going on with Japan and Sweden? Finally, I would be
set up to make reasoned choices about the next steps I might take if I
wanted to estimate, say, a single coefficient representing how the
relationship between education and participation changes on average
across countries. Although running and displaying 25 regressions (or
100) might be a daunting task in other statistical analysis
environments, I hope that I've shown (1) how \R~can make the tasks of
getting to know this kind of data easy. and (2) how an interesting
substantive story can be told simply and persuasively without an
asterisk in sight.

%\bibliography{/Users/jwbowers/Documents/BIB/jakes}
\bibliography{/Users/jake/Documents/BIB/jakes}

<<echo=FALSE>>=
#cleanup graphics windows
graphics.off()
@ 
\end{document}
